/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ShopProductSlugRouteImport } from './routes/shop.$productSlug'

const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/$productSlug',
  path: '/shop/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club/': typeof ClubIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club': typeof ClubIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club/': typeof ClubIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop/$productSlug'
    | '/club/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop/$productSlug'
    | '/club'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop/$productSlug'
    | '/club/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogosRoute: typeof LogosRoute
  SchoolRoute: typeof SchoolRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/shop/$productSlug': {
      id: '/shop/$productSlug'
      path: '/shop/$productSlug'
      fullPath: '/shop/$productSlug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubRouteChildren {
  ClubIndexRoute: typeof ClubIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubIndexRoute: ClubIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRouteWithChildren,
  LoginRoute: LoginRoute,
  LogosRoute: LogosRoute,
  SchoolRoute: SchoolRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
