/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ShopInfoRouteImport } from './routes/shop-info'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LikeLabRouteImport } from './routes/like-lab'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClubRouteImport } from './routes/club'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BloggerRouteImport } from './routes/blogger'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as HellPassIndexRouteImport } from './routes/hell-pass.index'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as BloggerIndexRouteImport } from './routes/blogger.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopProductSlugRouteImport } from './routes/shop.$productSlug'
import { Route as SchoolInstructorIdRouteImport } from './routes/school.$instructorId'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as PayGoRouteImport } from './routes/pay.go'
import { Route as PayFailRouteImport } from './routes/pay.fail'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRequisitesRouteImport } from './routes/legal.requisites'
import { Route as LegalPromoRulesRouteImport } from './routes/legal.promo-rules'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalOfferRouteImport } from './routes/legal.offer'
import { Route as HellPassTierRouteImport } from './routes/hell-pass.$tier'
import { Route as ClubTicketsRouteImport } from './routes/club.tickets'
import { Route as ClubSchoolRouteImport } from './routes/club.school'
import { Route as ClubRankRouteImport } from './routes/club.rank'
import { Route as ClubQuestsRouteImport } from './routes/club.quests'
import { Route as ClubMeRouteImport } from './routes/club.me'
import { Route as ClubInviteRouteImport } from './routes/club.invite'
import { Route as ClubInstallRouteImport } from './routes/club.install'
import { Route as ClubHellAiRouteImport } from './routes/club.hell-ai'
import { Route as ClubGarageRouteImport } from './routes/club.garage'
import { Route as ClubCheckoutRouteImport } from './routes/club.checkout'
import { Route as ClubCartRouteImport } from './routes/club.cart'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BloggerSettingsRouteImport } from './routes/blogger.settings'
import { Route as BloggerHellAiRouteImport } from './routes/blogger.hell-ai'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchoolRouteImport } from './routes/admin.school'
import { Route as AdminRafflesRouteImport } from './routes/admin.raffles'
import { Route as AdminQuestsRouteImport } from './routes/admin.quests'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminHellAiRouteImport } from './routes/admin.hell-ai'
import { Route as AdminFeedRouteImport } from './routes/admin.feed'
import { Route as AdminEconomyRouteImport } from './routes/admin.economy'
import { Route as AdminCdekRouteImport } from './routes/admin.cdek'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as ClubShopIndexRouteImport } from './routes/club.shop.index'
import { Route as ClubRafflesIndexRouteImport } from './routes/club.raffles.index'
import { Route as ClubOrdersIndexRouteImport } from './routes/club.orders.index'
import { Route as ClubHelpIndexRouteImport } from './routes/club.help.index'
import { Route as ClubHellPassIndexRouteImport } from './routes/club.hell-pass.index'
import { Route as BloggerRafflesIndexRouteImport } from './routes/blogger.raffles.index'
import { Route as ClubUNickRouteImport } from './routes/club.u.$nick'
import { Route as ClubShopProductSlugRouteImport } from './routes/club.shop.$productSlug'
import { Route as ClubRafflesRaffleIdRouteImport } from './routes/club.raffles.$raffleId'
import { Route as ClubPPostIdRouteImport } from './routes/club.p.$postId'
import { Route as ClubOrdersOrderIdRouteImport } from './routes/club.orders.$orderId'
import { Route as ClubLegalRequisitesRouteImport } from './routes/club.legal.requisites'
import { Route as ClubLegalPromoRulesRouteImport } from './routes/club.legal.promo-rules'
import { Route as ClubLegalPrivacyRouteImport } from './routes/club.legal.privacy'
import { Route as ClubHelpNewRouteImport } from './routes/club.help.new'
import { Route as ClubHelpTicketIdRouteImport } from './routes/club.help.$ticketId'
import { Route as ClubHellPassTierRouteImport } from './routes/club.hell-pass.$tier'
import { Route as BloggerRafflesRaffleIdRouteImport } from './routes/blogger.raffles.$raffleId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopInfoRoute = ShopInfoRouteImport.update({
  id: '/shop-info',
  path: '/shop-info',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeLabRoute = LikeLabRouteImport.update({
  id: '/like-lab',
  path: '/like-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggerRoute = BloggerRouteImport.update({
  id: '/blogger',
  path: '/blogger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const HellPassIndexRoute = HellPassIndexRouteImport.update({
  id: '/hell-pass/',
  path: '/hell-pass/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggerIndexRoute = BloggerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BloggerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/$productSlug',
  path: '/shop/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolInstructorIdRoute = SchoolInstructorIdRouteImport.update({
  id: '/$instructorId',
  path: '/$instructorId',
  getParentRoute: () => SchoolRoute,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PayGoRoute = PayGoRouteImport.update({
  id: '/pay/go',
  path: '/pay/go',
  getParentRoute: () => rootRouteImport,
} as any)
const PayFailRoute = PayFailRouteImport.update({
  id: '/pay/fail',
  path: '/pay/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRequisitesRoute = LegalRequisitesRouteImport.update({
  id: '/legal/requisites',
  path: '/legal/requisites',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPromoRulesRoute = LegalPromoRulesRouteImport.update({
  id: '/legal/promo-rules',
  path: '/legal/promo-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalOfferRoute = LegalOfferRouteImport.update({
  id: '/legal/offer',
  path: '/legal/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const HellPassTierRoute = HellPassTierRouteImport.update({
  id: '/hell-pass/$tier',
  path: '/hell-pass/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubTicketsRoute = ClubTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ClubRoute,
} as any)
const ClubSchoolRoute = ClubSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRankRoute = ClubRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => ClubRoute,
} as any)
const ClubQuestsRoute = ClubQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMeRoute = ClubMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ClubRoute,
} as any)
const ClubInviteRoute = ClubInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => ClubRoute,
} as any)
const ClubInstallRoute = ClubInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellAiRoute = ClubHellAiRouteImport.update({
  id: '/hell-ai',
  path: '/hell-ai',
  getParentRoute: () => ClubRoute,
} as any)
const ClubGarageRoute = ClubGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => ClubRoute,
} as any)
const ClubCheckoutRoute = ClubCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ClubRoute,
} as any)
const ClubCartRoute = ClubCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ClubRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggerSettingsRoute = BloggerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BloggerRoute,
} as any)
const BloggerHellAiRoute = BloggerHellAiRouteImport.update({
  id: '/hell-ai',
  path: '/hell-ai',
  getParentRoute: () => BloggerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolRoute = AdminSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRafflesRoute = AdminRafflesRouteImport.update({
  id: '/raffles',
  path: '/raffles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestsRoute = AdminQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHellAiRoute = AdminHellAiRouteImport.update({
  id: '/hell-ai',
  path: '/hell-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedRoute = AdminFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCdekRoute = AdminCdekRouteImport.update({
  id: '/cdek',
  path: '/cdek',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const ClubShopIndexRoute = ClubShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRafflesIndexRoute = ClubRafflesIndexRouteImport.update({
  id: '/raffles/',
  path: '/raffles/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubOrdersIndexRoute = ClubOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHelpIndexRoute = ClubHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellPassIndexRoute = ClubHellPassIndexRouteImport.update({
  id: '/hell-pass/',
  path: '/hell-pass/',
  getParentRoute: () => ClubRoute,
} as any)
const BloggerRafflesIndexRoute = BloggerRafflesIndexRouteImport.update({
  id: '/raffles/',
  path: '/raffles/',
  getParentRoute: () => BloggerRoute,
} as any)
const ClubUNickRoute = ClubUNickRouteImport.update({
  id: '/u/$nick',
  path: '/u/$nick',
  getParentRoute: () => ClubRoute,
} as any)
const ClubShopProductSlugRoute = ClubShopProductSlugRouteImport.update({
  id: '/shop/$productSlug',
  path: '/shop/$productSlug',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRafflesRaffleIdRoute = ClubRafflesRaffleIdRouteImport.update({
  id: '/raffles/$raffleId',
  path: '/raffles/$raffleId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubPPostIdRoute = ClubPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubOrdersOrderIdRoute = ClubOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubLegalRequisitesRoute = ClubLegalRequisitesRouteImport.update({
  id: '/legal/requisites',
  path: '/legal/requisites',
  getParentRoute: () => ClubRoute,
} as any)
const ClubLegalPromoRulesRoute = ClubLegalPromoRulesRouteImport.update({
  id: '/legal/promo-rules',
  path: '/legal/promo-rules',
  getParentRoute: () => ClubRoute,
} as any)
const ClubLegalPrivacyRoute = ClubLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHelpNewRoute = ClubHelpNewRouteImport.update({
  id: '/help/new',
  path: '/help/new',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHelpTicketIdRoute = ClubHelpTicketIdRouteImport.update({
  id: '/help/$ticketId',
  path: '/help/$ticketId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellPassTierRoute = ClubHellPassTierRouteImport.update({
  id: '/hell-pass/$tier',
  path: '/hell-pass/$tier',
  getParentRoute: () => ClubRoute,
} as any)
const BloggerRafflesRaffleIdRoute = BloggerRafflesRaffleIdRouteImport.update({
  id: '/raffles/$raffleId',
  path: '/raffles/$raffleId',
  getParentRoute: () => BloggerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogger': typeof BloggerRouteWithChildren
  '/cart': typeof CartRoute
  '/club': typeof ClubRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/like-lab': typeof LikeLabRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRouteWithChildren
  '/shop-info': typeof ShopInfoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cdek': typeof AdminCdekRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/hell-ai': typeof AdminHellAiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/raffles': typeof AdminRafflesRoute
  '/admin/school': typeof AdminSchoolRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogger/hell-ai': typeof BloggerHellAiRoute
  '/blogger/settings': typeof BloggerSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/club/cart': typeof ClubCartRoute
  '/club/checkout': typeof ClubCheckoutRoute
  '/club/garage': typeof ClubGarageRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/install': typeof ClubInstallRoute
  '/club/invite': typeof ClubInviteRoute
  '/club/me': typeof ClubMeRoute
  '/club/quests': typeof ClubQuestsRoute
  '/club/rank': typeof ClubRankRoute
  '/club/school': typeof ClubSchoolRoute
  '/club/tickets': typeof ClubTicketsRoute
  '/hell-pass/$tier': typeof HellPassTierRoute
  '/legal/offer': typeof LegalOfferRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/promo-rules': typeof LegalPromoRulesRoute
  '/legal/requisites': typeof LegalRequisitesRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/go': typeof PayGoRoute
  '/pay/success': typeof PaySuccessRoute
  '/school/$instructorId': typeof SchoolInstructorIdRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogger/': typeof BloggerIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/club/': typeof ClubIndexRoute
  '/hell-pass/': typeof HellPassIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/blogger/raffles/$raffleId': typeof BloggerRafflesRaffleIdRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/help/$ticketId': typeof ClubHelpTicketIdRoute
  '/club/help/new': typeof ClubHelpNewRoute
  '/club/legal/privacy': typeof ClubLegalPrivacyRoute
  '/club/legal/promo-rules': typeof ClubLegalPromoRulesRoute
  '/club/legal/requisites': typeof ClubLegalRequisitesRoute
  '/club/orders/$orderId': typeof ClubOrdersOrderIdRoute
  '/club/p/$postId': typeof ClubPPostIdRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/shop/$productSlug': typeof ClubShopProductSlugRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/blogger/raffles/': typeof BloggerRafflesIndexRoute
  '/club/hell-pass/': typeof ClubHellPassIndexRoute
  '/club/help/': typeof ClubHelpIndexRoute
  '/club/orders/': typeof ClubOrdersIndexRoute
  '/club/raffles/': typeof ClubRafflesIndexRoute
  '/club/shop/': typeof ClubShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/like-lab': typeof LikeLabRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRouteWithChildren
  '/shop-info': typeof ShopInfoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cdek': typeof AdminCdekRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/hell-ai': typeof AdminHellAiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/raffles': typeof AdminRafflesRoute
  '/admin/school': typeof AdminSchoolRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogger/hell-ai': typeof BloggerHellAiRoute
  '/blogger/settings': typeof BloggerSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/club/cart': typeof ClubCartRoute
  '/club/checkout': typeof ClubCheckoutRoute
  '/club/garage': typeof ClubGarageRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/install': typeof ClubInstallRoute
  '/club/invite': typeof ClubInviteRoute
  '/club/me': typeof ClubMeRoute
  '/club/quests': typeof ClubQuestsRoute
  '/club/rank': typeof ClubRankRoute
  '/club/school': typeof ClubSchoolRoute
  '/club/tickets': typeof ClubTicketsRoute
  '/hell-pass/$tier': typeof HellPassTierRoute
  '/legal/offer': typeof LegalOfferRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/promo-rules': typeof LegalPromoRulesRoute
  '/legal/requisites': typeof LegalRequisitesRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/go': typeof PayGoRoute
  '/pay/success': typeof PaySuccessRoute
  '/school/$instructorId': typeof SchoolInstructorIdRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogger': typeof BloggerIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/club': typeof ClubIndexRoute
  '/hell-pass': typeof HellPassIndexRoute
  '/shop': typeof ShopIndexRoute
  '/blogger/raffles/$raffleId': typeof BloggerRafflesRaffleIdRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/help/$ticketId': typeof ClubHelpTicketIdRoute
  '/club/help/new': typeof ClubHelpNewRoute
  '/club/legal/privacy': typeof ClubLegalPrivacyRoute
  '/club/legal/promo-rules': typeof ClubLegalPromoRulesRoute
  '/club/legal/requisites': typeof ClubLegalRequisitesRoute
  '/club/orders/$orderId': typeof ClubOrdersOrderIdRoute
  '/club/p/$postId': typeof ClubPPostIdRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/shop/$productSlug': typeof ClubShopProductSlugRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/blogger/raffles': typeof BloggerRafflesIndexRoute
  '/club/hell-pass': typeof ClubHellPassIndexRoute
  '/club/help': typeof ClubHelpIndexRoute
  '/club/orders': typeof ClubOrdersIndexRoute
  '/club/raffles': typeof ClubRafflesIndexRoute
  '/club/shop': typeof ClubShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogger': typeof BloggerRouteWithChildren
  '/cart': typeof CartRoute
  '/club': typeof ClubRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/like-lab': typeof LikeLabRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRouteWithChildren
  '/shop-info': typeof ShopInfoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cdek': typeof AdminCdekRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/hell-ai': typeof AdminHellAiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quests': typeof AdminQuestsRoute
  '/admin/raffles': typeof AdminRafflesRoute
  '/admin/school': typeof AdminSchoolRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogger/hell-ai': typeof BloggerHellAiRoute
  '/blogger/settings': typeof BloggerSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/club/cart': typeof ClubCartRoute
  '/club/checkout': typeof ClubCheckoutRoute
  '/club/garage': typeof ClubGarageRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/install': typeof ClubInstallRoute
  '/club/invite': typeof ClubInviteRoute
  '/club/me': typeof ClubMeRoute
  '/club/quests': typeof ClubQuestsRoute
  '/club/rank': typeof ClubRankRoute
  '/club/school': typeof ClubSchoolRoute
  '/club/tickets': typeof ClubTicketsRoute
  '/hell-pass/$tier': typeof HellPassTierRoute
  '/legal/offer': typeof LegalOfferRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/promo-rules': typeof LegalPromoRulesRoute
  '/legal/requisites': typeof LegalRequisitesRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/go': typeof PayGoRoute
  '/pay/success': typeof PaySuccessRoute
  '/school/$instructorId': typeof SchoolInstructorIdRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogger/': typeof BloggerIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/club/': typeof ClubIndexRoute
  '/hell-pass/': typeof HellPassIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/blogger/raffles/$raffleId': typeof BloggerRafflesRaffleIdRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/help/$ticketId': typeof ClubHelpTicketIdRoute
  '/club/help/new': typeof ClubHelpNewRoute
  '/club/legal/privacy': typeof ClubLegalPrivacyRoute
  '/club/legal/promo-rules': typeof ClubLegalPromoRulesRoute
  '/club/legal/requisites': typeof ClubLegalRequisitesRoute
  '/club/orders/$orderId': typeof ClubOrdersOrderIdRoute
  '/club/p/$postId': typeof ClubPPostIdRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/shop/$productSlug': typeof ClubShopProductSlugRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/blogger/raffles/': typeof BloggerRafflesIndexRoute
  '/club/hell-pass/': typeof ClubHellPassIndexRoute
  '/club/help/': typeof ClubHelpIndexRoute
  '/club/orders/': typeof ClubOrdersIndexRoute
  '/club/raffles/': typeof ClubRafflesIndexRoute
  '/club/shop/': typeof ClubShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogger'
    | '/cart'
    | '/club'
    | '/forgot-password'
    | '/like-lab'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop-info'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/cdek'
    | '/admin/economy'
    | '/admin/feed'
    | '/admin/hell-ai'
    | '/admin/orders'
    | '/admin/quests'
    | '/admin/raffles'
    | '/admin/school'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/tickets'
    | '/admin/users'
    | '/blogger/hell-ai'
    | '/blogger/settings'
    | '/checkout/success'
    | '/club/cart'
    | '/club/checkout'
    | '/club/garage'
    | '/club/hell-ai'
    | '/club/install'
    | '/club/invite'
    | '/club/me'
    | '/club/quests'
    | '/club/rank'
    | '/club/school'
    | '/club/tickets'
    | '/hell-pass/$tier'
    | '/legal/offer'
    | '/legal/privacy'
    | '/legal/promo-rules'
    | '/legal/requisites'
    | '/legal/terms'
    | '/pay/fail'
    | '/pay/go'
    | '/pay/success'
    | '/school/$instructorId'
    | '/shop/$productSlug'
    | '/admin/'
    | '/blogger/'
    | '/checkout/'
    | '/club/'
    | '/hell-pass/'
    | '/shop/'
    | '/blogger/raffles/$raffleId'
    | '/club/hell-pass/$tier'
    | '/club/help/$ticketId'
    | '/club/help/new'
    | '/club/legal/privacy'
    | '/club/legal/promo-rules'
    | '/club/legal/requisites'
    | '/club/orders/$orderId'
    | '/club/p/$postId'
    | '/club/raffles/$raffleId'
    | '/club/shop/$productSlug'
    | '/club/u/$nick'
    | '/blogger/raffles/'
    | '/club/hell-pass/'
    | '/club/help/'
    | '/club/orders/'
    | '/club/raffles/'
    | '/club/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/forgot-password'
    | '/like-lab'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop-info'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/cdek'
    | '/admin/economy'
    | '/admin/feed'
    | '/admin/hell-ai'
    | '/admin/orders'
    | '/admin/quests'
    | '/admin/raffles'
    | '/admin/school'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/tickets'
    | '/admin/users'
    | '/blogger/hell-ai'
    | '/blogger/settings'
    | '/checkout/success'
    | '/club/cart'
    | '/club/checkout'
    | '/club/garage'
    | '/club/hell-ai'
    | '/club/install'
    | '/club/invite'
    | '/club/me'
    | '/club/quests'
    | '/club/rank'
    | '/club/school'
    | '/club/tickets'
    | '/hell-pass/$tier'
    | '/legal/offer'
    | '/legal/privacy'
    | '/legal/promo-rules'
    | '/legal/requisites'
    | '/legal/terms'
    | '/pay/fail'
    | '/pay/go'
    | '/pay/success'
    | '/school/$instructorId'
    | '/shop/$productSlug'
    | '/admin'
    | '/blogger'
    | '/checkout'
    | '/club'
    | '/hell-pass'
    | '/shop'
    | '/blogger/raffles/$raffleId'
    | '/club/hell-pass/$tier'
    | '/club/help/$ticketId'
    | '/club/help/new'
    | '/club/legal/privacy'
    | '/club/legal/promo-rules'
    | '/club/legal/requisites'
    | '/club/orders/$orderId'
    | '/club/p/$postId'
    | '/club/raffles/$raffleId'
    | '/club/shop/$productSlug'
    | '/club/u/$nick'
    | '/blogger/raffles'
    | '/club/hell-pass'
    | '/club/help'
    | '/club/orders'
    | '/club/raffles'
    | '/club/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blogger'
    | '/cart'
    | '/club'
    | '/forgot-password'
    | '/like-lab'
    | '/login'
    | '/logos'
    | '/school'
    | '/shop-info'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/cdek'
    | '/admin/economy'
    | '/admin/feed'
    | '/admin/hell-ai'
    | '/admin/orders'
    | '/admin/quests'
    | '/admin/raffles'
    | '/admin/school'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/tickets'
    | '/admin/users'
    | '/blogger/hell-ai'
    | '/blogger/settings'
    | '/checkout/success'
    | '/club/cart'
    | '/club/checkout'
    | '/club/garage'
    | '/club/hell-ai'
    | '/club/install'
    | '/club/invite'
    | '/club/me'
    | '/club/quests'
    | '/club/rank'
    | '/club/school'
    | '/club/tickets'
    | '/hell-pass/$tier'
    | '/legal/offer'
    | '/legal/privacy'
    | '/legal/promo-rules'
    | '/legal/requisites'
    | '/legal/terms'
    | '/pay/fail'
    | '/pay/go'
    | '/pay/success'
    | '/school/$instructorId'
    | '/shop/$productSlug'
    | '/admin/'
    | '/blogger/'
    | '/checkout/'
    | '/club/'
    | '/hell-pass/'
    | '/shop/'
    | '/blogger/raffles/$raffleId'
    | '/club/hell-pass/$tier'
    | '/club/help/$ticketId'
    | '/club/help/new'
    | '/club/legal/privacy'
    | '/club/legal/promo-rules'
    | '/club/legal/requisites'
    | '/club/orders/$orderId'
    | '/club/p/$postId'
    | '/club/raffles/$raffleId'
    | '/club/shop/$productSlug'
    | '/club/u/$nick'
    | '/blogger/raffles/'
    | '/club/hell-pass/'
    | '/club/help/'
    | '/club/orders/'
    | '/club/raffles/'
    | '/club/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BloggerRoute: typeof BloggerRouteWithChildren
  CartRoute: typeof CartRoute
  ClubRoute: typeof ClubRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LikeLabRoute: typeof LikeLabRoute
  LoginRoute: typeof LoginRoute
  LogosRoute: typeof LogosRoute
  SchoolRoute: typeof SchoolRouteWithChildren
  ShopInfoRoute: typeof ShopInfoRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  HellPassTierRoute: typeof HellPassTierRoute
  LegalOfferRoute: typeof LegalOfferRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalPromoRulesRoute: typeof LegalPromoRulesRoute
  LegalRequisitesRoute: typeof LegalRequisitesRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PayFailRoute: typeof PayFailRoute
  PayGoRoute: typeof PayGoRoute
  PaySuccessRoute: typeof PaySuccessRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  HellPassIndexRoute: typeof HellPassIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-info': {
      id: '/shop-info'
      path: '/shop-info'
      fullPath: '/shop-info'
      preLoaderRoute: typeof ShopInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/like-lab': {
      id: '/like-lab'
      path: '/like-lab'
      fullPath: '/like-lab'
      preLoaderRoute: typeof LikeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogger': {
      id: '/blogger'
      path: '/blogger'
      fullPath: '/blogger'
      preLoaderRoute: typeof BloggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hell-pass/': {
      id: '/hell-pass/'
      path: '/hell-pass'
      fullPath: '/hell-pass/'
      preLoaderRoute: typeof HellPassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogger/': {
      id: '/blogger/'
      path: '/'
      fullPath: '/blogger/'
      preLoaderRoute: typeof BloggerIndexRouteImport
      parentRoute: typeof BloggerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/$productSlug': {
      id: '/shop/$productSlug'
      path: '/shop/$productSlug'
      fullPath: '/shop/$productSlug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$instructorId': {
      id: '/school/$instructorId'
      path: '/$instructorId'
      fullPath: '/school/$instructorId'
      preLoaderRoute: typeof SchoolInstructorIdRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/go': {
      id: '/pay/go'
      path: '/pay/go'
      fullPath: '/pay/go'
      preLoaderRoute: typeof PayGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/fail': {
      id: '/pay/fail'
      path: '/pay/fail'
      fullPath: '/pay/fail'
      preLoaderRoute: typeof PayFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/requisites': {
      id: '/legal/requisites'
      path: '/legal/requisites'
      fullPath: '/legal/requisites'
      preLoaderRoute: typeof LegalRequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/promo-rules': {
      id: '/legal/promo-rules'
      path: '/legal/promo-rules'
      fullPath: '/legal/promo-rules'
      preLoaderRoute: typeof LegalPromoRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/offer': {
      id: '/legal/offer'
      path: '/legal/offer'
      fullPath: '/legal/offer'
      preLoaderRoute: typeof LegalOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hell-pass/$tier': {
      id: '/hell-pass/$tier'
      path: '/hell-pass/$tier'
      fullPath: '/hell-pass/$tier'
      preLoaderRoute: typeof HellPassTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/tickets': {
      id: '/club/tickets'
      path: '/tickets'
      fullPath: '/club/tickets'
      preLoaderRoute: typeof ClubTicketsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/school': {
      id: '/club/school'
      path: '/school'
      fullPath: '/club/school'
      preLoaderRoute: typeof ClubSchoolRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/rank': {
      id: '/club/rank'
      path: '/rank'
      fullPath: '/club/rank'
      preLoaderRoute: typeof ClubRankRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/quests': {
      id: '/club/quests'
      path: '/quests'
      fullPath: '/club/quests'
      preLoaderRoute: typeof ClubQuestsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/me': {
      id: '/club/me'
      path: '/me'
      fullPath: '/club/me'
      preLoaderRoute: typeof ClubMeRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/invite': {
      id: '/club/invite'
      path: '/invite'
      fullPath: '/club/invite'
      preLoaderRoute: typeof ClubInviteRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/install': {
      id: '/club/install'
      path: '/install'
      fullPath: '/club/install'
      preLoaderRoute: typeof ClubInstallRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-ai': {
      id: '/club/hell-ai'
      path: '/hell-ai'
      fullPath: '/club/hell-ai'
      preLoaderRoute: typeof ClubHellAiRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/garage': {
      id: '/club/garage'
      path: '/garage'
      fullPath: '/club/garage'
      preLoaderRoute: typeof ClubGarageRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/checkout': {
      id: '/club/checkout'
      path: '/checkout'
      fullPath: '/club/checkout'
      preLoaderRoute: typeof ClubCheckoutRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/cart': {
      id: '/club/cart'
      path: '/cart'
      fullPath: '/club/cart'
      preLoaderRoute: typeof ClubCartRouteImport
      parentRoute: typeof ClubRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogger/settings': {
      id: '/blogger/settings'
      path: '/settings'
      fullPath: '/blogger/settings'
      preLoaderRoute: typeof BloggerSettingsRouteImport
      parentRoute: typeof BloggerRoute
    }
    '/blogger/hell-ai': {
      id: '/blogger/hell-ai'
      path: '/hell-ai'
      fullPath: '/blogger/hell-ai'
      preLoaderRoute: typeof BloggerHellAiRouteImport
      parentRoute: typeof BloggerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/school': {
      id: '/admin/school'
      path: '/school'
      fullPath: '/admin/school'
      preLoaderRoute: typeof AdminSchoolRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/raffles': {
      id: '/admin/raffles'
      path: '/raffles'
      fullPath: '/admin/raffles'
      preLoaderRoute: typeof AdminRafflesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quests': {
      id: '/admin/quests'
      path: '/quests'
      fullPath: '/admin/quests'
      preLoaderRoute: typeof AdminQuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hell-ai': {
      id: '/admin/hell-ai'
      path: '/hell-ai'
      fullPath: '/admin/hell-ai'
      preLoaderRoute: typeof AdminHellAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feed': {
      id: '/admin/feed'
      path: '/feed'
      fullPath: '/admin/feed'
      preLoaderRoute: typeof AdminFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cdek': {
      id: '/admin/cdek'
      path: '/cdek'
      fullPath: '/admin/cdek'
      preLoaderRoute: typeof AdminCdekRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/club/shop/': {
      id: '/club/shop/'
      path: '/shop'
      fullPath: '/club/shop/'
      preLoaderRoute: typeof ClubShopIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/raffles/': {
      id: '/club/raffles/'
      path: '/raffles'
      fullPath: '/club/raffles/'
      preLoaderRoute: typeof ClubRafflesIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/orders/': {
      id: '/club/orders/'
      path: '/orders'
      fullPath: '/club/orders/'
      preLoaderRoute: typeof ClubOrdersIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/help/': {
      id: '/club/help/'
      path: '/help'
      fullPath: '/club/help/'
      preLoaderRoute: typeof ClubHelpIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-pass/': {
      id: '/club/hell-pass/'
      path: '/hell-pass'
      fullPath: '/club/hell-pass/'
      preLoaderRoute: typeof ClubHellPassIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/blogger/raffles/': {
      id: '/blogger/raffles/'
      path: '/raffles'
      fullPath: '/blogger/raffles/'
      preLoaderRoute: typeof BloggerRafflesIndexRouteImport
      parentRoute: typeof BloggerRoute
    }
    '/club/u/$nick': {
      id: '/club/u/$nick'
      path: '/u/$nick'
      fullPath: '/club/u/$nick'
      preLoaderRoute: typeof ClubUNickRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/shop/$productSlug': {
      id: '/club/shop/$productSlug'
      path: '/shop/$productSlug'
      fullPath: '/club/shop/$productSlug'
      preLoaderRoute: typeof ClubShopProductSlugRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/raffles/$raffleId': {
      id: '/club/raffles/$raffleId'
      path: '/raffles/$raffleId'
      fullPath: '/club/raffles/$raffleId'
      preLoaderRoute: typeof ClubRafflesRaffleIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/p/$postId': {
      id: '/club/p/$postId'
      path: '/p/$postId'
      fullPath: '/club/p/$postId'
      preLoaderRoute: typeof ClubPPostIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/orders/$orderId': {
      id: '/club/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/club/orders/$orderId'
      preLoaderRoute: typeof ClubOrdersOrderIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/legal/requisites': {
      id: '/club/legal/requisites'
      path: '/legal/requisites'
      fullPath: '/club/legal/requisites'
      preLoaderRoute: typeof ClubLegalRequisitesRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/legal/promo-rules': {
      id: '/club/legal/promo-rules'
      path: '/legal/promo-rules'
      fullPath: '/club/legal/promo-rules'
      preLoaderRoute: typeof ClubLegalPromoRulesRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/legal/privacy': {
      id: '/club/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/club/legal/privacy'
      preLoaderRoute: typeof ClubLegalPrivacyRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/help/new': {
      id: '/club/help/new'
      path: '/help/new'
      fullPath: '/club/help/new'
      preLoaderRoute: typeof ClubHelpNewRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/help/$ticketId': {
      id: '/club/help/$ticketId'
      path: '/help/$ticketId'
      fullPath: '/club/help/$ticketId'
      preLoaderRoute: typeof ClubHelpTicketIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-pass/$tier': {
      id: '/club/hell-pass/$tier'
      path: '/hell-pass/$tier'
      fullPath: '/club/hell-pass/$tier'
      preLoaderRoute: typeof ClubHellPassTierRouteImport
      parentRoute: typeof ClubRoute
    }
    '/blogger/raffles/$raffleId': {
      id: '/blogger/raffles/$raffleId'
      path: '/raffles/$raffleId'
      fullPath: '/blogger/raffles/$raffleId'
      preLoaderRoute: typeof BloggerRafflesRaffleIdRouteImport
      parentRoute: typeof BloggerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCdekRoute: typeof AdminCdekRoute
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminFeedRoute: typeof AdminFeedRoute
  AdminHellAiRoute: typeof AdminHellAiRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminQuestsRoute: typeof AdminQuestsRoute
  AdminRafflesRoute: typeof AdminRafflesRoute
  AdminSchoolRoute: typeof AdminSchoolRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCdekRoute: AdminCdekRoute,
  AdminEconomyRoute: AdminEconomyRoute,
  AdminFeedRoute: AdminFeedRoute,
  AdminHellAiRoute: AdminHellAiRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminQuestsRoute: AdminQuestsRoute,
  AdminRafflesRoute: AdminRafflesRoute,
  AdminSchoolRoute: AdminSchoolRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BloggerRouteChildren {
  BloggerHellAiRoute: typeof BloggerHellAiRoute
  BloggerSettingsRoute: typeof BloggerSettingsRoute
  BloggerIndexRoute: typeof BloggerIndexRoute
  BloggerRafflesRaffleIdRoute: typeof BloggerRafflesRaffleIdRoute
  BloggerRafflesIndexRoute: typeof BloggerRafflesIndexRoute
}

const BloggerRouteChildren: BloggerRouteChildren = {
  BloggerHellAiRoute: BloggerHellAiRoute,
  BloggerSettingsRoute: BloggerSettingsRoute,
  BloggerIndexRoute: BloggerIndexRoute,
  BloggerRafflesRaffleIdRoute: BloggerRafflesRaffleIdRoute,
  BloggerRafflesIndexRoute: BloggerRafflesIndexRoute,
}

const BloggerRouteWithChildren =
  BloggerRoute._addFileChildren(BloggerRouteChildren)

interface ClubRouteChildren {
  ClubCartRoute: typeof ClubCartRoute
  ClubCheckoutRoute: typeof ClubCheckoutRoute
  ClubGarageRoute: typeof ClubGarageRoute
  ClubHellAiRoute: typeof ClubHellAiRoute
  ClubInstallRoute: typeof ClubInstallRoute
  ClubInviteRoute: typeof ClubInviteRoute
  ClubMeRoute: typeof ClubMeRoute
  ClubQuestsRoute: typeof ClubQuestsRoute
  ClubRankRoute: typeof ClubRankRoute
  ClubSchoolRoute: typeof ClubSchoolRoute
  ClubTicketsRoute: typeof ClubTicketsRoute
  ClubIndexRoute: typeof ClubIndexRoute
  ClubHellPassTierRoute: typeof ClubHellPassTierRoute
  ClubHelpTicketIdRoute: typeof ClubHelpTicketIdRoute
  ClubHelpNewRoute: typeof ClubHelpNewRoute
  ClubLegalPrivacyRoute: typeof ClubLegalPrivacyRoute
  ClubLegalPromoRulesRoute: typeof ClubLegalPromoRulesRoute
  ClubLegalRequisitesRoute: typeof ClubLegalRequisitesRoute
  ClubOrdersOrderIdRoute: typeof ClubOrdersOrderIdRoute
  ClubPPostIdRoute: typeof ClubPPostIdRoute
  ClubRafflesRaffleIdRoute: typeof ClubRafflesRaffleIdRoute
  ClubShopProductSlugRoute: typeof ClubShopProductSlugRoute
  ClubUNickRoute: typeof ClubUNickRoute
  ClubHellPassIndexRoute: typeof ClubHellPassIndexRoute
  ClubHelpIndexRoute: typeof ClubHelpIndexRoute
  ClubOrdersIndexRoute: typeof ClubOrdersIndexRoute
  ClubRafflesIndexRoute: typeof ClubRafflesIndexRoute
  ClubShopIndexRoute: typeof ClubShopIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubCartRoute: ClubCartRoute,
  ClubCheckoutRoute: ClubCheckoutRoute,
  ClubGarageRoute: ClubGarageRoute,
  ClubHellAiRoute: ClubHellAiRoute,
  ClubInstallRoute: ClubInstallRoute,
  ClubInviteRoute: ClubInviteRoute,
  ClubMeRoute: ClubMeRoute,
  ClubQuestsRoute: ClubQuestsRoute,
  ClubRankRoute: ClubRankRoute,
  ClubSchoolRoute: ClubSchoolRoute,
  ClubTicketsRoute: ClubTicketsRoute,
  ClubIndexRoute: ClubIndexRoute,
  ClubHellPassTierRoute: ClubHellPassTierRoute,
  ClubHelpTicketIdRoute: ClubHelpTicketIdRoute,
  ClubHelpNewRoute: ClubHelpNewRoute,
  ClubLegalPrivacyRoute: ClubLegalPrivacyRoute,
  ClubLegalPromoRulesRoute: ClubLegalPromoRulesRoute,
  ClubLegalRequisitesRoute: ClubLegalRequisitesRoute,
  ClubOrdersOrderIdRoute: ClubOrdersOrderIdRoute,
  ClubPPostIdRoute: ClubPPostIdRoute,
  ClubRafflesRaffleIdRoute: ClubRafflesRaffleIdRoute,
  ClubShopProductSlugRoute: ClubShopProductSlugRoute,
  ClubUNickRoute: ClubUNickRoute,
  ClubHellPassIndexRoute: ClubHellPassIndexRoute,
  ClubHelpIndexRoute: ClubHelpIndexRoute,
  ClubOrdersIndexRoute: ClubOrdersIndexRoute,
  ClubRafflesIndexRoute: ClubRafflesIndexRoute,
  ClubShopIndexRoute: ClubShopIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface SchoolRouteChildren {
  SchoolInstructorIdRoute: typeof SchoolInstructorIdRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolInstructorIdRoute: SchoolInstructorIdRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BloggerRoute: BloggerRouteWithChildren,
  CartRoute: CartRoute,
  ClubRoute: ClubRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LikeLabRoute: LikeLabRoute,
  LoginRoute: LoginRoute,
  LogosRoute: LogosRoute,
  SchoolRoute: SchoolRouteWithChildren,
  ShopInfoRoute: ShopInfoRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  HellPassTierRoute: HellPassTierRoute,
  LegalOfferRoute: LegalOfferRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalPromoRulesRoute: LegalPromoRulesRoute,
  LegalRequisitesRoute: LegalRequisitesRoute,
  LegalTermsRoute: LegalTermsRoute,
  PayFailRoute: PayFailRoute,
  PayGoRoute: PayGoRoute,
  PaySuccessRoute: PaySuccessRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  HellPassIndexRoute: HellPassIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
