/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ShopProductSlugRouteImport } from './routes/shop.$productSlug'
import { Route as ClubSchoolRouteImport } from './routes/club.school'
import { Route as ClubMeRouteImport } from './routes/club.me'
import { Route as ClubHellAiRouteImport } from './routes/club.hell-ai'
import { Route as ClubRafflesIndexRouteImport } from './routes/club.raffles.index'
import { Route as ClubHellPassIndexRouteImport } from './routes/club.hell-pass.index'
import { Route as ClubUNickRouteImport } from './routes/club.u.$nick'
import { Route as ClubRafflesRaffleIdRouteImport } from './routes/club.raffles.$raffleId'
import { Route as ClubHellPassTierRouteImport } from './routes/club.hell-pass.$tier'

const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/$productSlug',
  path: '/shop/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubSchoolRoute = ClubSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMeRoute = ClubMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellAiRoute = ClubHellAiRouteImport.update({
  id: '/hell-ai',
  path: '/hell-ai',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRafflesIndexRoute = ClubRafflesIndexRouteImport.update({
  id: '/raffles/',
  path: '/raffles/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellPassIndexRoute = ClubHellPassIndexRouteImport.update({
  id: '/hell-pass/',
  path: '/hell-pass/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubUNickRoute = ClubUNickRouteImport.update({
  id: '/u/$nick',
  path: '/u/$nick',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRafflesRaffleIdRoute = ClubRafflesRaffleIdRouteImport.update({
  id: '/raffles/$raffleId',
  path: '/raffles/$raffleId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubHellPassTierRoute = ClubHellPassTierRouteImport.update({
  id: '/hell-pass/$tier',
  path: '/hell-pass/$tier',
  getParentRoute: () => ClubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/me': typeof ClubMeRoute
  '/club/school': typeof ClubSchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club/': typeof ClubIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/club/hell-pass/': typeof ClubHellPassIndexRoute
  '/club/raffles/': typeof ClubRafflesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/me': typeof ClubMeRoute
  '/club/school': typeof ClubSchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club': typeof ClubIndexRoute
  '/shop': typeof ShopIndexRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/club/hell-pass': typeof ClubHellPassIndexRoute
  '/club/raffles': typeof ClubRafflesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/school': typeof SchoolRoute
  '/club/hell-ai': typeof ClubHellAiRoute
  '/club/me': typeof ClubMeRoute
  '/club/school': typeof ClubSchoolRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/club/': typeof ClubIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/club/hell-pass/$tier': typeof ClubHellPassTierRoute
  '/club/raffles/$raffleId': typeof ClubRafflesRaffleIdRoute
  '/club/u/$nick': typeof ClubUNickRoute
  '/club/hell-pass/': typeof ClubHellPassIndexRoute
  '/club/raffles/': typeof ClubRafflesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/login'
    | '/logos'
    | '/school'
    | '/club/hell-ai'
    | '/club/me'
    | '/club/school'
    | '/shop/$productSlug'
    | '/club/'
    | '/shop/'
    | '/club/hell-pass/$tier'
    | '/club/raffles/$raffleId'
    | '/club/u/$nick'
    | '/club/hell-pass/'
    | '/club/raffles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logos'
    | '/school'
    | '/club/hell-ai'
    | '/club/me'
    | '/club/school'
    | '/shop/$productSlug'
    | '/club'
    | '/shop'
    | '/club/hell-pass/$tier'
    | '/club/raffles/$raffleId'
    | '/club/u/$nick'
    | '/club/hell-pass'
    | '/club/raffles'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/login'
    | '/logos'
    | '/school'
    | '/club/hell-ai'
    | '/club/me'
    | '/club/school'
    | '/shop/$productSlug'
    | '/club/'
    | '/shop/'
    | '/club/hell-pass/$tier'
    | '/club/raffles/$raffleId'
    | '/club/u/$nick'
    | '/club/hell-pass/'
    | '/club/raffles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogosRoute: typeof LogosRoute
  SchoolRoute: typeof SchoolRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/shop/$productSlug': {
      id: '/shop/$productSlug'
      path: '/shop/$productSlug'
      fullPath: '/shop/$productSlug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/school': {
      id: '/club/school'
      path: '/school'
      fullPath: '/club/school'
      preLoaderRoute: typeof ClubSchoolRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/me': {
      id: '/club/me'
      path: '/me'
      fullPath: '/club/me'
      preLoaderRoute: typeof ClubMeRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-ai': {
      id: '/club/hell-ai'
      path: '/hell-ai'
      fullPath: '/club/hell-ai'
      preLoaderRoute: typeof ClubHellAiRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/raffles/': {
      id: '/club/raffles/'
      path: '/raffles'
      fullPath: '/club/raffles/'
      preLoaderRoute: typeof ClubRafflesIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-pass/': {
      id: '/club/hell-pass/'
      path: '/hell-pass'
      fullPath: '/club/hell-pass/'
      preLoaderRoute: typeof ClubHellPassIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/u/$nick': {
      id: '/club/u/$nick'
      path: '/u/$nick'
      fullPath: '/club/u/$nick'
      preLoaderRoute: typeof ClubUNickRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/raffles/$raffleId': {
      id: '/club/raffles/$raffleId'
      path: '/raffles/$raffleId'
      fullPath: '/club/raffles/$raffleId'
      preLoaderRoute: typeof ClubRafflesRaffleIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/hell-pass/$tier': {
      id: '/club/hell-pass/$tier'
      path: '/hell-pass/$tier'
      fullPath: '/club/hell-pass/$tier'
      preLoaderRoute: typeof ClubHellPassTierRouteImport
      parentRoute: typeof ClubRoute
    }
  }
}

interface ClubRouteChildren {
  ClubHellAiRoute: typeof ClubHellAiRoute
  ClubMeRoute: typeof ClubMeRoute
  ClubSchoolRoute: typeof ClubSchoolRoute
  ClubIndexRoute: typeof ClubIndexRoute
  ClubHellPassTierRoute: typeof ClubHellPassTierRoute
  ClubRafflesRaffleIdRoute: typeof ClubRafflesRaffleIdRoute
  ClubUNickRoute: typeof ClubUNickRoute
  ClubHellPassIndexRoute: typeof ClubHellPassIndexRoute
  ClubRafflesIndexRoute: typeof ClubRafflesIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubHellAiRoute: ClubHellAiRoute,
  ClubMeRoute: ClubMeRoute,
  ClubSchoolRoute: ClubSchoolRoute,
  ClubIndexRoute: ClubIndexRoute,
  ClubHellPassTierRoute: ClubHellPassTierRoute,
  ClubRafflesRaffleIdRoute: ClubRafflesRaffleIdRoute,
  ClubUNickRoute: ClubUNickRoute,
  ClubHellPassIndexRoute: ClubHellPassIndexRoute,
  ClubRafflesIndexRoute: ClubRafflesIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRouteWithChildren,
  LoginRoute: LoginRoute,
  LogosRoute: LogosRoute,
  SchoolRoute: SchoolRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
